#             BC
#     ------------------
# BL |7    6   5   4   3| BR
#    |8     ZONES      2|
# FL |9   10  11  12   1| FR
#     ------------------
#             FC

settings:
  update_rate: 250 #550 # Rate limit the requests to prevent overloading the bulb
  max_brightness: 100
  sensitivity: 10
  effect: 'smooth' # 'sudden' or 'smooth'
  duration: 500    # The duration of the effect, in milliseconds. The
                   # minimum is 30. This is ignored for sudden effects.
  draw_debug_window: true
bulbs:
  - name: Front Left
    ip: '192.168.1.101'
    zones:
      - 9
      - 10
      - 11
      - 12
      - 1
  - name: Front Center
    ip: '192.168.1.110'
    zones:
      - 9
      - 10
      - 11
      - 12
      - 1
      
  - name: Front Right
    ip: '192.168.1.107'
    zones:
      - 9
      - 10
      - 11
      - 12
      - 1
  - name: Back Right
    ip: '192.168.1.81'
    zones:
      - 7
      - 6
      - 5
      - 4
      - 3
  - name: Back Center
    ip: '192.168.1.83'
    zones:
      - 7
      - 6
      - 5
      - 4
      - 3  
  - name: Back Left
    ip: '192.168.1.75'
    zones:
      - 7
      - 6
      - 5
      - 4
      - 3
#         
#   - name: Tree
#     ip: '192.168.1.79'
#     zones:
#       - 8
#       - 7
#       - 9
#       
#   - name: Sloth
#     ip: '192.168.1.86'
#     zones:
#       - 3
#       - 2
#       - 1

